nome = str(input('Digite seu nome: ')).strip()
print('Seu nome maiúsculo: {}'.format(nome.upper()))
print('Seu nome em minúsculo: {}'.format(nome.lower()))
frase = nome.split()
nome = ''.join(frase)
print('Quantidade de letras em seu nome: {}'.format(len(nome) - nome.count(' ')))
print('Quantidade de letras em seu primeiro nome: {}'.format(len(frase[0])))